### ISSUE TITLE
BUG: атрибут hasPrivateKey=true даже после извлечения токена с ключом

### ISSUE THREAD

**Issue by Gwinkamp** [kaluga-astral/cryptopro-cades#22]
**ОКРУЖЕНИЕ:**
dev
https://kaluga-astral.github.io/services/

**ШАГИ ВОСПРОИЗВЕДЕНИЯ:**
Предусловие: 
* установлен КриптоПро 5.0.12000
* установлен CBP версии 2.0.14530
* есть токен с ключом

1. подключить токен к ПК
2. открыть стенд https://kaluga-astral.github.io/services/
3. нажать "показать сертификаты"
4. найти в списке сертификат с токена => `hasPrivateKey=true`, Ok
5. отсоединить токен от ПК
6. перезагрузить страницу
7. нажать "показать сертификаты"
8. найти в списке этот же сертификат с токена

**ФАКТИЧЕСКИЙ РЕЗУЛЬТАТ:**
 `hasPrivateKey=true`, хотя подключения к закрытому ключу уже нет (подтверждается нажатием кнопки "проверить шифрование/расшифровку")
![image](https://user-images.githubusercontent.com/41391970/170274371-3e534a2f-a1d7-47a2-834e-312d17bc4363.png)

**ОЖИДАЕМЫЙ РЕЗУЛЬТАТ:**
после извлечения токена с закрытым ключом  `hasPrivateKey=false`
по аналогии с тулбокс - там после извлечения флаг сбрасывается

**Comment by mt89vein** [comment]
Я не нашел адекватного способа повлиять на этот флаг из кода. В интернете тоже пусто, как будто никто не сталкивался с этой проблемой))

Если вытащить usb и смотреть в сертификатах от майкрософт, он там тоже показывает что есть закрытый ключ. Хотя его по факту нет. Можно конечно пытаться получать наименование контейнера (путь до него), но тогда криптопро станет на каждый сертификат просить вставить USB токен. Если у клиента есть много сертов и мало usb портов (не может всё воткнуть), то у тебя на каждую операцию запроса списка сертов будет появляться окно - имхо это крайне негативно скажется на пользователях. В идеале нужно требовать только тот серт который у клиента зарегистрирован в системе, но у нас это сделать проблематично.

Проблемы с флагом нет, если не добавлять открытую часть сертификата в личные (в реестр). [Но работает это не всегда - может перестать работать сертификат и нужно будет переставить серт через окно криптопро]
При этом при вставленном токене сертификат становится виден.

**Comment by Gwinkamp** [comment]
Боль будет у пользователей с множеством организаций на учетке: когда им будут приходить входящие транзакции, фронт будет видеть ключи с hasPrivateKey = true и слать им запросы на расшифровку, тем самым заспамив пользователя сообщениями с просьбой вставить носитель.

На данном этапе проблема неактуальна, так как у первых пользователей этой либы будет по одной организации на учетке и они будут понимать какой токен подключить.

Частично эту проблему сгладит реализация задачи https://astraltrack.atlassian.net/browse/AR5-6372

**Comment by va4es2** [comment]
Решил проблему - https://github.com/kaluga-astral/services/pull/47
