### ISSUE TITLE
BUG: Ошибка при подписи большого файла

### ISSUE THREAD

**Issue by Gwinkamp** [kaluga-astral/cryptopro-cades#27]
**ОКРУЖЕНИЕ:**
dev
https://kaluga-astral.github.io/services/

**ШАГИ ВОСПРОИЗВЕДЕНИЯ:**
Предусловия:
* установлен КриптоПро 5.0.12000
* установлен CBP версии 2.0.14530
* есть сертификат с закрытым ключом

1. открыть стенд https://kaluga-astral.github.io/services/
2. выбрать сертификат с закрытым ключом
3. приложить любой файл в 100 Мб
4. нажать "Подпись CMS"

**ФАКТИЧЕСКИЙ РЕЗУЛЬТАТ:**
файл подписи успешно сформируется, но в консоли возникает ошибка:
![image](https://user-images.githubusercontent.com/41391970/170982310-114877cc-1d73-4790-bd7d-5fc3df63bd17.png)

**ОЖИДАЕМЫЙ РЕЗУЛЬТАТ:**
файл подписи успешно сформируется и никаких ошибок не возникнет

**PS:**
50Мб подписывает без ошибки, дело в размере файла, я полагаю

**Comment by mt89vein** [comment]
Большие файлы лучше будет подписывать через вычисление хэшей на сервере и подпись хэша (десяток байт на клиенте), так как у нас все подписи открепленные, мы можем это позволить себе. Там лимит объёма файла уже будет зависеть от возможностей сервера :)

Из [доки криптопро](https://docs.cryptopro.ru/cades/plugin/content-encoding?id=%d0%9e%d0%b3%d1%80%d0%b0%d0%bd%d0%b8%d1%87%d0%b5%d0%bd%d0%b8%d1%8f-%d1%80%d0%b0%d0%b7%d0%bc%d0%b5%d1%80%d0%b0-%d0%bf%d0%be%d0%b4%d0%bf%d0%b8%d1%81%d1%8b%d0%b2%d0%b0%d0%b5%d0%bc%d1%8b%d1%85-%d0%b4%d0%b0%d0%bd%d0%bd%d1%8b%d1%85)

Ограничения размера подписываемых данных
В зависимости от конфигурации компьютера (используемая оперативная память, количество открытых вкладок браузера и т.п.) размер файлов, которые возможно будет подписать вариируется от 10 МБ до 60 МБ. Если есть необходимость подписания файлов большего размера, то рекомендуется использовать Подпись файла с использованием FileAPI

FileApi мы технически не можем использовать. Если только не перенесём этап подписания документа до импорта.. правда редактировать тогда документы не сможем :)

Неизвестную ошибку я подправил, там теперь CBP-11: Потеряно соединение с КриптоПро ЭЦП Browser plug-in.
вместо lost connection to extension
